// Generated by gencpp from file robot_coordination/AddPath.msg
// DO NOT EDIT!


#ifndef ROBOT_COORDINATION_MESSAGE_ADDPATH_H
#define ROBOT_COORDINATION_MESSAGE_ADDPATH_H

#include <ros/service_traits.h>


#include <robot_coordination/AddPathRequest.h>
#include <robot_coordination/AddPathResponse.h>


namespace robot_coordination
{

struct AddPath
{

typedef AddPathRequest Request;
typedef AddPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddPath
} // namespace robot_coordination


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_coordination::AddPath > {
  static const char* value()
  {
    return "131b0547a79043bf206c558dae4c0162";
  }

  static const char* value(const ::robot_coordination::AddPath&) { return value(); }
};

template<>
struct DataType< ::robot_coordination::AddPath > {
  static const char* value()
  {
    return "robot_coordination/AddPath";
  }

  static const char* value(const ::robot_coordination::AddPath&) { return value(); }
};


// service_traits::MD5Sum< ::robot_coordination::AddPathRequest> should match 
// service_traits::MD5Sum< ::robot_coordination::AddPath > 
template<>
struct MD5Sum< ::robot_coordination::AddPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_coordination::AddPath >::value();
  }
  static const char* value(const ::robot_coordination::AddPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_coordination::AddPathRequest> should match 
// service_traits::DataType< ::robot_coordination::AddPath > 
template<>
struct DataType< ::robot_coordination::AddPathRequest>
{
  static const char* value()
  {
    return DataType< ::robot_coordination::AddPath >::value();
  }
  static const char* value(const ::robot_coordination::AddPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_coordination::AddPathResponse> should match 
// service_traits::MD5Sum< ::robot_coordination::AddPath > 
template<>
struct MD5Sum< ::robot_coordination::AddPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_coordination::AddPath >::value();
  }
  static const char* value(const ::robot_coordination::AddPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_coordination::AddPathResponse> should match 
// service_traits::DataType< ::robot_coordination::AddPath > 
template<>
struct DataType< ::robot_coordination::AddPathResponse>
{
  static const char* value()
  {
    return DataType< ::robot_coordination::AddPath >::value();
  }
  static const char* value(const ::robot_coordination::AddPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COORDINATION_MESSAGE_ADDPATH_H
