// Generated by gencpp from file robot_coordination/AddPathRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_COORDINATION_MESSAGE_ADDPATHREQUEST_H
#define ROBOT_COORDINATION_MESSAGE_ADDPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_coordination/Waypoint.h>

namespace robot_coordination
{
template <class ContainerAllocator>
struct AddPathRequest_
{
  typedef AddPathRequest_<ContainerAllocator> Type;

  AddPathRequest_()
    : waypoints()  {
    }
  AddPathRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_coordination::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_coordination::Waypoint_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::robot_coordination::AddPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_coordination::AddPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddPathRequest_

typedef ::robot_coordination::AddPathRequest_<std::allocator<void> > AddPathRequest;

typedef boost::shared_ptr< ::robot_coordination::AddPathRequest > AddPathRequestPtr;
typedef boost::shared_ptr< ::robot_coordination::AddPathRequest const> AddPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_coordination::AddPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_coordination::AddPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_coordination

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_coordination': ['/home/casch/turtle/src/mkr2018_mrc/robot_coordination/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::AddPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::AddPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::AddPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98cb2a6107fcdd1191f76ae34e6888f6";
  }

  static const char* value(const ::robot_coordination::AddPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98cb2a6107fcdd11ULL;
  static const uint64_t static_value2 = 0x91f76ae34e6888f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_coordination/AddPathRequest";
  }

  static const char* value(const ::robot_coordination::AddPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Waypoint[] waypoints\n\
\n\
================================================================================\n\
MSG: robot_coordination/Waypoint\n\
geometry_msgs/Pose pose\n\
duration timepoint\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::robot_coordination::AddPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_coordination::AddPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_coordination::AddPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_coordination::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COORDINATION_MESSAGE_ADDPATHREQUEST_H
