// Generated by gencpp from file robot_coordination/StopMovementResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_COORDINATION_MESSAGE_STOPMOVEMENTRESPONSE_H
#define ROBOT_COORDINATION_MESSAGE_STOPMOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_coordination
{
template <class ContainerAllocator>
struct StopMovementResponse_
{
  typedef StopMovementResponse_<ContainerAllocator> Type;

  StopMovementResponse_()
    : ack(false)  {
    }
  StopMovementResponse_(const ContainerAllocator& _alloc)
    : ack(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::robot_coordination::StopMovementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_coordination::StopMovementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopMovementResponse_

typedef ::robot_coordination::StopMovementResponse_<std::allocator<void> > StopMovementResponse;

typedef boost::shared_ptr< ::robot_coordination::StopMovementResponse > StopMovementResponsePtr;
typedef boost::shared_ptr< ::robot_coordination::StopMovementResponse const> StopMovementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_coordination::StopMovementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_coordination

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_coordination': ['/home/casch/turtle/src/mkr2018_mrc/robot_coordination/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::StopMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::StopMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::StopMovementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5729177853f34b146e2e57766d4dc2";
  }

  static const char* value(const ::robot_coordination::StopMovementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5729177853f34bULL;
  static const uint64_t static_value2 = 0x146e2e57766d4dc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_coordination/StopMovementResponse";
  }

  static const char* value(const ::robot_coordination::StopMovementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ack\n\
\n\
";
  }

  static const char* value(const ::robot_coordination::StopMovementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopMovementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_coordination::StopMovementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_coordination::StopMovementResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COORDINATION_MESSAGE_STOPMOVEMENTRESPONSE_H
