// Generated by gencpp from file robot_coordination/StopMovement.msg
// DO NOT EDIT!


#ifndef ROBOT_COORDINATION_MESSAGE_STOPMOVEMENT_H
#define ROBOT_COORDINATION_MESSAGE_STOPMOVEMENT_H

#include <ros/service_traits.h>


#include <robot_coordination/StopMovementRequest.h>
#include <robot_coordination/StopMovementResponse.h>


namespace robot_coordination
{

struct StopMovement
{

typedef StopMovementRequest Request;
typedef StopMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopMovement
} // namespace robot_coordination


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_coordination::StopMovement > {
  static const char* value()
  {
    return "8f5729177853f34b146e2e57766d4dc2";
  }

  static const char* value(const ::robot_coordination::StopMovement&) { return value(); }
};

template<>
struct DataType< ::robot_coordination::StopMovement > {
  static const char* value()
  {
    return "robot_coordination/StopMovement";
  }

  static const char* value(const ::robot_coordination::StopMovement&) { return value(); }
};


// service_traits::MD5Sum< ::robot_coordination::StopMovementRequest> should match 
// service_traits::MD5Sum< ::robot_coordination::StopMovement > 
template<>
struct MD5Sum< ::robot_coordination::StopMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_coordination::StopMovement >::value();
  }
  static const char* value(const ::robot_coordination::StopMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_coordination::StopMovementRequest> should match 
// service_traits::DataType< ::robot_coordination::StopMovement > 
template<>
struct DataType< ::robot_coordination::StopMovementRequest>
{
  static const char* value()
  {
    return DataType< ::robot_coordination::StopMovement >::value();
  }
  static const char* value(const ::robot_coordination::StopMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_coordination::StopMovementResponse> should match 
// service_traits::MD5Sum< ::robot_coordination::StopMovement > 
template<>
struct MD5Sum< ::robot_coordination::StopMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_coordination::StopMovement >::value();
  }
  static const char* value(const ::robot_coordination::StopMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_coordination::StopMovementResponse> should match 
// service_traits::DataType< ::robot_coordination::StopMovement > 
template<>
struct DataType< ::robot_coordination::StopMovementResponse>
{
  static const char* value()
  {
    return DataType< ::robot_coordination::StopMovement >::value();
  }
  static const char* value(const ::robot_coordination::StopMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COORDINATION_MESSAGE_STOPMOVEMENT_H
