// Generated by gencpp from file robot_coordination/Waypoint.msg
// DO NOT EDIT!


#ifndef ROBOT_COORDINATION_MESSAGE_WAYPOINT_H
#define ROBOT_COORDINATION_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace robot_coordination
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : pose()
    , timepoint()  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , timepoint()  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef ros::Duration _timepoint_type;
  _timepoint_type timepoint;





  typedef boost::shared_ptr< ::robot_coordination::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_coordination::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::robot_coordination::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::robot_coordination::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::robot_coordination::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_coordination::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_coordination::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_coordination

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_coordination': ['/home/casch/turtle/src/mkr2018_mrc/robot_coordination/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_coordination::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_coordination::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_coordination::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_coordination::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82b1fd005964132ed04c925157225818";
  }

  static const char* value(const ::robot_coordination::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82b1fd005964132eULL;
  static const uint64_t static_value2 = 0xd04c925157225818ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_coordination::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_coordination/Waypoint";
  }

  static const char* value(const ::robot_coordination::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_coordination::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
duration timepoint\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::robot_coordination::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_coordination::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.timepoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_coordination::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_coordination::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "timepoint: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.timepoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COORDINATION_MESSAGE_WAYPOINT_H
