(cl:defpackage robot_coordination-srv
  (:use )
  (:export
   "ADDPATH"
   "<ADDPATH-REQUEST>"
   "ADDPATH-REQUEST"
   "<ADDPATH-RESPONSE>"
   "ADDPATH-RESPONSE"
   "STARTMOVEMENT"
   "<STARTMOVEMENT-REQUEST>"
   "STARTMOVEMENT-REQUEST"
   "<STARTMOVEMENT-RESPONSE>"
   "STARTMOVEMENT-RESPONSE"
   "STOPMOVEMENT"
   "<STOPMOVEMENT-REQUEST>"
   "STOPMOVEMENT-REQUEST"
   "<STOPMOVEMENT-RESPONSE>"
   "STOPMOVEMENT-RESPONSE"
  ))

